pages = [{"l":"index.html#","e":false,"i":"","n":"argparse","t":"argparse","d":"","k":"static"},
{"l":"argparse.html#","e":false,"i":"","n":"argparse","t":"argparse","d":"","k":"package"},
{"l":"argparse.html#main-66a","e":false,"i":"","n":"main","t":"main[Container](instance: Container, args: Iterable[String], env: Map[String, String]): Unit","d":"argparse","k":"def"},
{"l":"argparse/Argument.html#","e":false,"i":"","n":"Argument","t":"Argument[A](name: String) extends () => A","d":"argparse","k":"class"},
{"l":"argparse/Argument.html#apply-993","e":false,"i":"","n":"apply","t":"apply(): A","d":"argparse.Argument","k":"def"},
{"l":"argparse/Argument.html#value-0","e":false,"i":"","n":"value","t":"value: A","d":"argparse.Argument","k":"def"},
{"l":"argparse/BashCompleter.html#","e":false,"i":"","n":"BashCompleter","t":"BashCompleter","d":"argparse","k":"trait"},
{"l":"argparse/BashCompleter$.html#","e":false,"i":"","n":"BashCompleter","t":"BashCompleter","d":"argparse","k":"object"},
{"l":"argparse/BashCompleter$$Default$.html#","e":false,"i":"","n":"Default","t":"Default extends BashCompleter","d":"argparse.BashCompleter","k":"object"},
{"l":"argparse/BashCompleter$$Empty$.html#","e":false,"i":"","n":"Empty","t":"Empty extends BashCompleter","d":"argparse.BashCompleter","k":"object"},
{"l":"argparse/BashCompleter$$Fixed.html#","e":false,"i":"","n":"Fixed","t":"Fixed(alternatives: Set[String]) extends BashCompleter","d":"argparse.BashCompleter","k":"class"},
{"l":"argparse/BashCompleter$$Raw.html#","e":false,"i":"","n":"Raw","t":"Raw(script: String) extends BashCompleter","d":"argparse.BashCompleter","k":"class"},
{"l":"argparse/ParseResult.html#","e":false,"i":"","n":"ParseResult","t":"ParseResult","d":"argparse","k":"trait"},
{"l":"argparse/ParseResult$.html#","e":false,"i":"","n":"ParseResult","t":"ParseResult","d":"argparse","k":"object"},
{"l":"argparse/ParseResult$$EarlyExit$.html#","e":false,"i":"","n":"EarlyExit","t":"EarlyExit extends ParseResult","d":"argparse.ParseResult","k":"object"},
{"l":"argparse/ParseResult$$Error$.html#","e":false,"i":"","n":"Error","t":"Error extends ParseResult","d":"argparse.ParseResult","k":"object"},
{"l":"argparse/ParseResult$$Success$.html#","e":false,"i":"","n":"Success","t":"Success extends ParseResult","d":"argparse.ParseResult","k":"object"},
{"l":"argparse/alias.html#","e":false,"i":"","n":"alias","t":"alias(aliases: String*) extends StaticAnnotation","d":"argparse","k":"class"},
{"l":"argparse/default$.html#","e":false,"i":"","n":"default","t":"default extends Api","d":"argparse","k":"object"},
{"l":"argparse/dirs.html#","e":false,"i":"","n":"dirs","t":"dirs(name: String, system: Boolean)","d":"argparse","k":"class"},
{"l":"argparse/dirs.html#cache-0","e":false,"i":"","n":"cache","t":"cache: Path","d":"argparse.dirs","k":"def"},
{"l":"argparse/dirs.html#config-0","e":false,"i":"","n":"config","t":"config: List[Path]","d":"argparse.dirs","k":"def"},
{"l":"argparse/dirs.html#data-0","e":false,"i":"","n":"data","t":"data: List[Path]","d":"argparse.dirs","k":"def"},
{"l":"argparse/dirs.html#log-0","e":false,"i":"","n":"log","t":"log: Path","d":"argparse.dirs","k":"def"},
{"l":"argparse/dirs.html#runtime-0","e":false,"i":"","n":"runtime","t":"runtime: Path","d":"argparse.dirs","k":"def"},
{"l":"argparse/dirs.html#state-0","e":false,"i":"","n":"state","t":"state: Path","d":"argparse.dirs","k":"def"},
{"l":"argparse/dirs$.html#","e":false,"i":"","n":"dirs","t":"dirs","d":"argparse","k":"object"},
{"l":"argparse/dirs$.html#guessSystem-0","e":false,"i":"","n":"guessSystem","t":"guessSystem: Boolean","d":"argparse.dirs","k":"def"},
{"l":"argparse/env.html#","e":false,"i":"","n":"env","t":"env(env: String) extends StaticAnnotation","d":"argparse","k":"class"},
{"l":"argparse/name.html#","e":false,"i":"","n":"name","t":"name(name: String) extends StaticAnnotation","d":"argparse","k":"class"},
{"l":"argparse/term$.html#","e":false,"i":"","n":"term","t":"term","d":"argparse","k":"object"},
{"l":"argparse/term$.html#cols-0","e":false,"i":"","n":"cols","t":"cols: Int","d":"argparse.term","k":"def"},
{"l":"argparse/term$.html#getCols-fffff63d","e":false,"i":"","n":"getCols","t":"getCols(): Option[Int]","d":"argparse.term","k":"def"},
{"l":"argparse/term$.html#getRows-fffff63d","e":false,"i":"","n":"getRows","t":"getRows(): Option[Int]","d":"argparse.term","k":"def"},
{"l":"argparse/term$.html#rows-0","e":false,"i":"","n":"rows","t":"rows: Int","d":"argparse.term","k":"def"},
{"l":"argparse/userdirs$.html#","e":false,"i":"","n":"userdirs","t":"userdirs","d":"argparse","k":"object"},
{"l":"argparse/userdirs$.html#cacheHome-0","e":false,"i":"","n":"cacheHome","t":"cacheHome: Path","d":"argparse.userdirs","k":"def"},
{"l":"argparse/userdirs$.html#configDirs-0","e":false,"i":"","n":"configDirs","t":"configDirs: List[Path]","d":"argparse.userdirs","k":"def"},
{"l":"argparse/userdirs$.html#configHome-0","e":false,"i":"","n":"configHome","t":"configHome: Path","d":"argparse.userdirs","k":"def"},
{"l":"argparse/userdirs$.html#dataDirs-0","e":false,"i":"","n":"dataDirs","t":"dataDirs: List[Path]","d":"argparse.userdirs","k":"def"},
{"l":"argparse/userdirs$.html#dataHome-0","e":false,"i":"","n":"dataHome","t":"dataHome: Path","d":"argparse.userdirs","k":"def"},
{"l":"argparse/userdirs$.html#runtime-0","e":false,"i":"","n":"runtime","t":"runtime: Path","d":"argparse.userdirs","k":"def"},
{"l":"argparse/userdirs$$project.html#","e":false,"i":"","n":"project","t":"project(name: String)","d":"argparse.userdirs","k":"class"},
{"l":"argparse/userdirs$$project.html#cacheHome-0","e":false,"i":"","n":"cacheHome","t":"cacheHome: Path","d":"argparse.userdirs.project","k":"def"},
{"l":"argparse/userdirs$$project.html#configDirs-0","e":false,"i":"","n":"configDirs","t":"configDirs: List[Path]","d":"argparse.userdirs.project","k":"def"},
{"l":"argparse/userdirs$$project.html#configHome-0","e":false,"i":"","n":"configHome","t":"configHome: Path","d":"argparse.userdirs.project","k":"def"},
{"l":"argparse/userdirs$$project.html#dataDirs-0","e":false,"i":"","n":"dataDirs","t":"dataDirs: List[Path]","d":"argparse.userdirs.project","k":"def"},
{"l":"argparse/userdirs$$project.html#dataHome-0","e":false,"i":"","n":"dataHome","t":"dataHome: Path","d":"argparse.userdirs.project","k":"def"},
{"l":"argparse/userdirs$$project.html#runtime-0","e":false,"i":"","n":"runtime","t":"runtime: Path","d":"argparse.userdirs.project","k":"def"},
{"l":"argparse/xdg$.html#","e":false,"i":"","n":"xdg","t":"xdg","d":"argparse","k":"object"},
{"l":"argparse/core.html#","e":false,"i":"","n":"argparse.core","t":"argparse.core","d":"","k":"package"},
{"l":"argparse/core/Api.html#","e":false,"i":"","n":"Api","t":"Api extends TypesApi with ParsersApi with ReadersApi with VersionSpecificApi","d":"argparse.core","k":"trait"},
{"l":"argparse/core/Command.html#","e":false,"i":"","n":"Command","t":"Command[A](name: String, makeParser: (() => A) => ArgumentParser)","d":"argparse.core","k":"class"},
{"l":"argparse/core/Command.html#Container-0","e":false,"i":"","n":"Container","t":"Container = A","d":"argparse.core.Command","k":"type"},
{"l":"argparse/core/Command$.html#","e":false,"i":"","n":"Command","t":"Command","d":"argparse.core","k":"object"},
{"l":"argparse/core/Command$.html#entrypointImpl-2ea","e":false,"i":"","n":"entrypointImpl","t":"entrypointImpl[Container : Type](using Quotes)(instance: Expr[Container], args: Expr[Iterable[String]], env: Expr[Map[String, String]]): Expr[Unit]","d":"argparse.core.Command","k":"def"},
{"l":"argparse/core/DocComment.html#","e":false,"i":"","n":"DocComment","t":"DocComment(paragraphs: Iterable[String], params: Map[String, String])","d":"argparse.core","k":"class"},
{"l":"argparse/core/DocComment$.html#","e":false,"i":"","n":"DocComment","t":"DocComment","d":"argparse.core","k":"object"},
{"l":"argparse/core/DocComment$.html#extract-56a","e":false,"i":"","n":"extract","t":"extract(comment: String): DocComment","d":"argparse.core.DocComment","k":"def"},
{"l":"argparse/core/DocComment$.html#given_DocComment-0","e":false,"i":"","n":"given_DocComment","t":"given_DocComment: DocComment","d":"argparse.core.DocComment","k":"given"},
{"l":"argparse/core/DocComment$.html#here-9e","e":false,"i":"","n":"here","t":"here(using qctx: Quotes): Expr[DocComment]","d":"argparse.core.DocComment","k":"def"},
{"l":"argparse/core/InteractiveBashCompletion$.html#","e":false,"i":"","n":"InteractiveBashCompletion","t":"InteractiveBashCompletion","d":"argparse.core","k":"object"},
{"l":"argparse/core/InteractiveBashCompletion$.html#completeOrFalse-fffff1fd","e":false,"i":"","n":"completeOrFalse","t":"completeOrFalse(parser: ArgumentParser, env: Map[String, String], stdout: PrintStream): Boolean","d":"argparse.core.InteractiveBashCompletion","k":"def"},
{"l":"argparse/core/LowPrioPrinters.html#","e":false,"i":"","n":"LowPrioPrinters","t":"LowPrioPrinters","d":"argparse.core","k":"trait"},
{"l":"argparse/core/LowPrioPrinters.html#anyPrinter-376","e":false,"i":"","n":"anyPrinter","t":"anyPrinter[A]: anyPrinter[A]","d":"argparse.core.LowPrioPrinters","k":"given"},
{"l":"argparse/core/LowPrioReaders.html#","e":false,"i":"","n":"LowPrioReaders","t":"LowPrioReaders","d":"argparse.core","k":"trait"},
{"l":"argparse/core/LowPrioReaders.html#CollectionReader-fffff6f0","e":false,"i":"","n":"CollectionReader","t":"CollectionReader[Elem, Col <: (Iterable)](implicit elementReader: <none>[Elem], factory: Factory[Elem, Col[Elem]]): Reader[Col[Elem]]","d":"argparse.core.LowPrioReaders","k":"def"},
{"l":"argparse/core/MacroApi.html#","e":false,"i":"","n":"MacroApi","t":"MacroApi extends TypesApi with ParsersApi with OutputApi","d":"argparse.core","k":"trait"},
{"l":"argparse/core/MacroApi.html#alias-0","e":false,"i":"","n":"alias","t":"alias = alias","d":"argparse.core.MacroApi","k":"type"},
{"l":"argparse/core/MacroApi.html#alias-0","e":false,"i":"","n":"alias","t":"alias: alias.type","d":"argparse.core.MacroApi","k":"val"},
{"l":"argparse/core/MacroApi.html#env-0","e":false,"i":"","n":"env","t":"env = env","d":"argparse.core.MacroApi","k":"type"},
{"l":"argparse/core/MacroApi.html#env-0","e":false,"i":"","n":"env","t":"env: env.type","d":"argparse.core.MacroApi","k":"val"},
{"l":"argparse/core/MacroApi.html#name-0","e":false,"i":"","n":"name","t":"name = name","d":"argparse.core.MacroApi","k":"type"},
{"l":"argparse/core/MacroApi.html#name-0","e":false,"i":"","n":"name","t":"name: name.type","d":"argparse.core.MacroApi","k":"val"},
{"l":"argparse/core/MacroApi$command.html#","e":false,"i":"","n":"command","t":"command() extends StaticAnnotation","d":"argparse.core.MacroApi","k":"class"},
{"l":"argparse/core/MacroApi$unknownCommand.html#","e":false,"i":"","n":"unknownCommand","t":"unknownCommand() extends StaticAnnotation","d":"argparse.core.MacroApi","k":"class"},
{"l":"argparse/core/MacroUtil.html#","e":false,"i":"","n":"MacroUtil","t":"MacroUtil(using val qctx: Quotes)","d":"argparse.core","k":"class"},
{"l":"argparse/core/MacroUtil.html#callOrInstantiate-fffff160","e":false,"i":"","n":"callOrInstantiate","t":"callOrInstantiate(instance: Term, methodOrClass: Symbol, argss: Expr[List[List[_]]]): Term","d":"argparse.core.MacroUtil","k":"def"},
{"l":"argparse/core/MacroUtil.html#findAnnotated-5f","e":false,"i":"","n":"findAnnotated","t":"findAnnotated(tpe: TypeRepr): List[(Ref, Symbol)]","d":"argparse.core.MacroUtil","k":"def"},
{"l":"argparse/core/MacroUtil.html#getDefaultParams-fffff9ce","e":false,"i":"","n":"getDefaultParams","t":"getDefaultParams(instance: Term, method: Symbol): Map[Symbol, Term]","d":"argparse.core.MacroUtil","k":"def"},
{"l":"argparse/core/MacroUtil.html#makeArg-573","e":false,"i":"","n":"makeArg","t":"makeArg(api: Ref, param: Symbol, defaults: Map[Symbol, Term], docs: DocComment, parser: Expr[_]): Expr[() => ]","d":"argparse.core.MacroUtil","k":"def"},
{"l":"argparse/core/MacroUtil.html#makeArgs-8d9","e":false,"i":"","n":"makeArgs","t":"makeArgs(api: Ref, instance: Term, sym: Symbol, parser: Expr[_]): Expr[List[List[() => ]]]","d":"argparse.core.MacroUtil","k":"def"},
{"l":"argparse/core/MacroUtil.html#makeCommandForSym-fffffd52","e":false,"i":"","n":"makeCommandForSym","t":"makeCommandForSym[C : Type](api: Ref, sym: Symbol): Expr[Command[C]]","d":"argparse.core.MacroUtil","k":"def"},
{"l":"argparse/core/MacroUtil.html#makeCommands-fffff40b","e":false,"i":"","n":"makeCommands","t":"makeCommands[C : Type]: List[Expr[Command[_]]]","d":"argparse.core.MacroUtil","k":"def"},
{"l":"argparse/core/MacroUtil.html#qctx-0","e":false,"i":"","n":"qctx","t":"qctx: Quotes","d":"argparse.core.MacroUtil","k":"given"},
{"l":"argparse/core/OutputApi.html#","e":false,"i":"","n":"OutputApi","t":"OutputApi extends ParsersApi with TypesApi with Printers","d":"argparse.core","k":"trait"},
{"l":"argparse/core/OutputApi.html#handleError-19","e":false,"i":"","n":"handleError","t":"handleError(t: Throwable): Nothing","d":"argparse.core.OutputApi","k":"def"},
{"l":"argparse/core/OutputApi$Printer.html#","e":false,"i":"","n":"Printer","t":"Printer[A]","d":"argparse.core.OutputApi","k":"trait"},
{"l":"argparse/core/OutputApi$Printer.html#print-44a","e":false,"i":"","n":"print","t":"print(a: A, out: PrintStream): Unit","d":"argparse.core.OutputApi.Printer","k":"def"},
{"l":"argparse/core/OutputApi$.html#","e":false,"i":"","n":"OutputApi","t":"OutputApi","d":"argparse.core","k":"object"},
{"l":"argparse/core/OutputApi$.html#tabulate-25f","e":false,"i":"","n":"tabulate","t":"tabulate(rows: Iterable[Iterable[_]], header: Iterable[String], alignments: Iterable[Alignment]): String","d":"argparse.core.OutputApi","k":"def"},
{"l":"argparse/core/OutputApi$.html#tabulatep-25f","e":false,"i":"","n":"tabulatep","t":"tabulatep(rows: Iterable[Product], headers: Iterable[String], alignments: Iterable[Alignment]): String","d":"argparse.core.OutputApi","k":"def"},
{"l":"argparse/core/OutputApi$$Alignment.html#","e":false,"i":"","n":"Alignment","t":"Alignment","d":"argparse.core.OutputApi","k":"enum"},
{"l":"argparse/core/OutputApi$$Alignment.html#Left-0","e":false,"i":"","n":"Left","t":"Left extends Alignment","d":"argparse.core.OutputApi.Alignment","k":"case"},
{"l":"argparse/core/OutputApi$$Alignment.html#Right-0","e":false,"i":"","n":"Right","t":"Right extends Alignment","d":"argparse.core.OutputApi.Alignment","k":"case"},
{"l":"argparse/core/OutputApi$$Alignment.html#Numeric-0","e":false,"i":"","n":"Numeric","t":"Numeric extends Alignment","d":"argparse.core.OutputApi.Alignment","k":"case"},
{"l":"argparse/core/ParamInfo.html#","e":false,"i":"","n":"ParamInfo","t":"ParamInfo(isNamed: Boolean, names: Seq[String], argName: Option[String], repeats: Boolean, env: Option[String], description: String, interactiveCompleter: String => Seq[String], standaloneCompleter: BashCompleter)","d":"argparse.core","k":"class"},
{"l":"argparse/core/ParamInfo.html#isFlag-0","e":false,"i":"","n":"isFlag","t":"isFlag: Boolean","d":"argparse.core.ParamInfo","k":"def"},
{"l":"argparse/core/Parser$.html#","e":false,"i":"","n":"Parser","t":"Parser","d":"argparse.core","k":"object"},
{"l":"argparse/core/Parser$.html#parse-fffff35e","e":false,"i":"","n":"parse","t":"parse(params: Seq[ParamDef], args: Iterable[String], reportUnknown: String => Unit): Boolean","d":"argparse.core.Parser","k":"def"},
{"l":"argparse/core/Parser$$Continue$.html#","e":false,"i":"","n":"Continue","t":"Continue extends ParamResult","d":"argparse.core.Parser","k":"object"},
{"l":"argparse/core/Parser$$ParamDef.html#","e":false,"i":"","n":"ParamDef","t":"ParamDef(names: Seq[String], parseAndSet: (String, Option[String]) => ParamResult, missing: () => Unit, isFlag: Boolean, repeatPositional: Boolean, endOfNamed: Boolean)","d":"argparse.core.Parser","k":"class"},
{"l":"argparse/core/Parser$$ParamDef.html#isNamed-0","e":false,"i":"","n":"isNamed","t":"isNamed: Boolean","d":"argparse.core.Parser.ParamDef","k":"def"},
{"l":"argparse/core/Parser$$ParamResult.html#","e":false,"i":"","n":"ParamResult","t":"ParamResult","d":"argparse.core.Parser","k":"trait"},
{"l":"argparse/core/Parser$$Stop$.html#","e":false,"i":"","n":"Stop","t":"Stop extends ParamResult","d":"argparse.core.Parser","k":"object"},
{"l":"argparse/core/ParsersApi.html#","e":false,"i":"","n":"ParsersApi","t":"ParsersApi","d":"argparse.core","k":"trait"},
{"l":"argparse/core/ParsersApi.html#defaultBashCompletionFlags-0","e":false,"i":"","n":"defaultBashCompletionFlags","t":"defaultBashCompletionFlags: Seq[String]","d":"argparse.core.ParsersApi","k":"def"},
{"l":"argparse/core/ParsersApi.html#defaultHelpFlags-0","e":false,"i":"","n":"defaultHelpFlags","t":"defaultHelpFlags: Seq[String]","d":"argparse.core.ParsersApi","k":"def"},
{"l":"argparse/core/ParsersApi.html#defaultHelpMessage-9ab","e":false,"i":"","n":"defaultHelpMessage","t":"defaultHelpMessage(parser: ArgumentParser): String","d":"argparse.core.ParsersApi","k":"def"},
{"l":"argparse/core/ParsersApi.html#exit-b3e","e":false,"i":"","n":"exit","t":"exit(code: Int): Nothing","d":"argparse.core.ParsersApi","k":"def"},
{"l":"argparse/core/ParsersApi$ArgumentParser.html#","e":false,"i":"","n":"ArgumentParser","t":"ArgumentParser(val description: String, val helpFlags: Seq[String], val bashCompletionFlags: Seq[String])","d":"argparse.core.ParsersApi","k":"class"},
{"l":"argparse/core/ParsersApi$ArgumentParser.html#action-fffff8b6","e":false,"i":"","n":"action","t":"action(fn: => Unit): ArgumentParser.this.type","d":"argparse.core.ParsersApi.ArgumentParser","k":"def"},
{"l":"argparse/core/ParsersApi$ArgumentParser.html#addParamDef-fffff84b","e":false,"i":"","n":"addParamDef","t":"addParamDef(pdef: ParamDef): Unit","d":"argparse.core.ParsersApi.ArgumentParser","k":"def"},
{"l":"argparse/core/ParsersApi$ArgumentParser.html#addParamInfo-fffff829","e":false,"i":"","n":"addParamInfo","t":"addParamInfo(pinfo: ParamInfo): Unit","d":"argparse.core.ParsersApi.ArgumentParser","k":"def"},
{"l":"argparse/core/ParsersApi$ArgumentParser.html#addSubparser-fffff21a","e":false,"i":"","n":"addSubparser","t":"addSubparser(name: String, parser: ArgumentParser, aliases: Seq[String]): ArgumentParser.this.type","d":"argparse.core.ParsersApi.ArgumentParser","k":"def"},
{"l":"argparse/core/ParsersApi$ArgumentParser.html#bashCompletionFlags-0","e":false,"i":"","n":"bashCompletionFlags","t":"bashCompletionFlags: Seq[String]","d":"argparse.core.ParsersApi.ArgumentParser","k":"val"},
{"l":"argparse/core/ParsersApi$ArgumentParser.html#description-0","e":false,"i":"","n":"description","t":"description: String","d":"argparse.core.ParsersApi.ArgumentParser","k":"val"},
{"l":"argparse/core/ParsersApi$ArgumentParser.html#env-0","e":false,"i":"","n":"env","t":"env: Map[String, String]","d":"argparse.core.ParsersApi.ArgumentParser","k":"def"},
{"l":"argparse/core/ParsersApi$ArgumentParser.html#help-665","e":false,"i":"","n":"help","t":"help(): String","d":"argparse.core.ParsersApi.ArgumentParser","k":"def"},
{"l":"argparse/core/ParsersApi$ArgumentParser.html#help-fffff141","e":false,"i":"","n":"help","t":"help(message: String): ArgumentParser.this.type","d":"argparse.core.ParsersApi.ArgumentParser","k":"def"},
{"l":"argparse/core/ParsersApi$ArgumentParser.html#helpFlags-0","e":false,"i":"","n":"helpFlags","t":"helpFlags: Seq[String]","d":"argparse.core.ParsersApi.ArgumentParser","k":"val"},
{"l":"argparse/core/ParsersApi$ArgumentParser.html#param-957","e":false,"i":"","n":"param","t":"param[A](name: String, default: => A, env: String, aliases: Seq[String], help: String, flag: Boolean, endOfNamed: Boolean, interactiveCompleter: String => Seq[String], standaloneCompleter: BashCompleter, argName: String)(implicit reader: Reader[A]): Argument[A]","d":"argparse.core.ParsersApi.ArgumentParser","k":"def"},
{"l":"argparse/core/ParsersApi$ArgumentParser.html#paramDefs-0","e":false,"i":"","n":"paramDefs","t":"paramDefs: List[ParamDef]","d":"argparse.core.ParsersApi.ArgumentParser","k":"def"},
{"l":"argparse/core/ParsersApi$ArgumentParser.html#paramInfos-0","e":false,"i":"","n":"paramInfos","t":"paramInfos: List[ParamInfo]","d":"argparse.core.ParsersApi.ArgumentParser","k":"def"},
{"l":"argparse/core/ParsersApi$ArgumentParser.html#parseOrExit-48e","e":false,"i":"","n":"parseOrExit","t":"parseOrExit(args: Iterable[String], env: Map[String, String], stdout: PrintStream, stderr: PrintStream): Unit","d":"argparse.core.ParsersApi.ArgumentParser","k":"def"},
{"l":"argparse/core/ParsersApi$ArgumentParser.html#parseResult-f01","e":false,"i":"","n":"parseResult","t":"parseResult(args: Iterable[String], env: Map[String, String], stdout: PrintStream, stderr: PrintStream): ParseResult","d":"argparse.core.ParsersApi.ArgumentParser","k":"def"},
{"l":"argparse/core/ParsersApi$ArgumentParser.html#postCheck-fffffa74","e":false,"i":"","n":"postCheck","t":"postCheck(check: (Iterable[String], Map[String, String]) => Option[String]): ArgumentParser.this.type","d":"argparse.core.ParsersApi.ArgumentParser","k":"def"},
{"l":"argparse/core/ParsersApi$ArgumentParser.html#printBashCompletion-5a8","e":false,"i":"","n":"printBashCompletion","t":"printBashCompletion(out: PrintStream, commandChain: String*): Unit","d":"argparse.core.ParsersApi.ArgumentParser","k":"def"},
{"l":"argparse/core/ParsersApi$ArgumentParser.html#repeatedParam-fffff400","e":false,"i":"","n":"repeatedParam","t":"repeatedParam[A](name: String, aliases: Seq[String], help: String, flag: Boolean, endOfNamed: Boolean, interactiveCompleter: String => Seq[String], standaloneCompleter: BashCompleter, argName: String)(implicit reader: Reader[A]): Argument[Seq[A]]","d":"argparse.core.ParsersApi.ArgumentParser","k":"def"},
{"l":"argparse/core/ParsersApi$ArgumentParser.html#requiredParam-fffffc7b","e":false,"i":"","n":"requiredParam","t":"requiredParam[A](name: String, env: String, aliases: Seq[String], help: String, flag: Boolean, endOfNamed: Boolean, interactiveCompleter: String => Seq[String], standaloneCompleter: BashCompleter, argName: String)(implicit reader: Reader[A]): Argument[A]","d":"argparse.core.ParsersApi.ArgumentParser","k":"def"},
{"l":"argparse/core/ParsersApi$ArgumentParser.html#singleParam-93","e":false,"i":"","n":"singleParam","t":"singleParam[A](name: String, default: Option[() => A], env: Option[String], aliases: Seq[String], help: String, flag: Boolean, endOfNamed: Boolean, interactiveCompleter: Option[String => Seq[String]], standaloneCompleter: Option[BashCompleter], argName: Option[String])(implicit reader: Reader[A]): Argument[A]","d":"argparse.core.ParsersApi.ArgumentParser","k":"def"},
{"l":"argparse/core/ParsersApi$ArgumentParser.html#stderr-0","e":false,"i":"","n":"stderr","t":"stderr: PrintStream","d":"argparse.core.ParsersApi.ArgumentParser","k":"def"},
{"l":"argparse/core/ParsersApi$ArgumentParser.html#stdout-0","e":false,"i":"","n":"stdout","t":"stdout: PrintStream","d":"argparse.core.ParsersApi.ArgumentParser","k":"def"},
{"l":"argparse/core/ParsersApi$ArgumentParser.html#subparser-631","e":false,"i":"","n":"subparser","t":"subparser(name: String, description: String, aliases: Seq[String]): ArgumentParser","d":"argparse.core.ParsersApi.ArgumentParser","k":"def"},
{"l":"argparse/core/ParsersApi$ArgumentParser.html#subparserUnknown-fffffa74","e":false,"i":"","n":"subparserUnknown","t":"subparserUnknown(action: (String, Iterable[String]) => Unit): ArgumentParser.this.type","d":"argparse.core.ParsersApi.ArgumentParser","k":"def"},
{"l":"argparse/core/ParsersApi$ArgumentParser.html#subparsers-0","e":false,"i":"","n":"subparsers","t":"subparsers: Map[String, ArgumentParser]","d":"argparse.core.ParsersApi.ArgumentParser","k":"def"},
{"l":"argparse/core/ParsersApi$ArgumentParser$.html#","e":false,"i":"","n":"ArgumentParser","t":"ArgumentParser","d":"argparse.core.ParsersApi","k":"object"},
{"l":"argparse/core/ParsersApi$ArgumentParser$.html#apply-aeb","e":false,"i":"","n":"apply","t":"apply(description: String, helpFlags: Seq[String], bashCompletionFlags: Seq[String]): ArgumentParser","d":"argparse.core.ParsersApi.ArgumentParser","k":"def"},
{"l":"argparse/core/Printers.html#","e":false,"i":"","n":"Printers","t":"Printers extends LowPrioPrinters","d":"argparse.core","k":"trait"},
{"l":"argparse/core/Printers.html#given_Printer_Array-0","e":false,"i":"","n":"given_Printer_Array","t":"given_Printer_Array: given_Printer_Array.type","d":"argparse.core.Printers","k":"given"},
{"l":"argparse/core/Printers.html#given_Printer_Future-fffff72b","e":false,"i":"","n":"given_Printer_Future","t":"given_Printer_Future[A](using p: <none>[A]): given_Printer_Future[A]","d":"argparse.core.Printers","k":"given"},
{"l":"argparse/core/Printers.html#given_Printer_Generator-86b","e":false,"i":"","n":"given_Printer_Generator","t":"given_Printer_Generator[A](using p: <none>[A]): given_Printer_Generator[A]","d":"argparse.core.Printers","k":"given"},
{"l":"argparse/core/Printers.html#given_Printer_Unit-0","e":false,"i":"","n":"given_Printer_Unit","t":"given_Printer_Unit: given_Printer_Unit.type","d":"argparse.core.Printers","k":"given"},
{"l":"argparse/core/Printers.html#given_Printer_Writable-0","e":false,"i":"","n":"given_Printer_Writable","t":"given_Printer_Writable: given_Printer_Writable.type","d":"argparse.core.Printers","k":"given"},
{"l":"argparse/core/Printers.html#nonProductListPrinter-fffff7f8","e":false,"i":"","n":"nonProductListPrinter","t":"nonProductListPrinter[A <: Iterable[B], B](using elemPrinter: <none>[B]): nonProductListPrinter[A, B]","d":"argparse.core.Printers","k":"given"},
{"l":"argparse/core/Printers.html#productListPrinter-fffff986","e":false,"i":"","n":"productListPrinter","t":"productListPrinter[A <: Iterable[B], B <: Product](using m: ProductLabels[B]): productListPrinter[A, B]","d":"argparse.core.Printers","k":"given"},
{"l":"argparse/core/Printers$given_Printer_Array$.html#","e":false,"i":"","n":"given_Printer_Array","t":"given_Printer_Array extends Printer[Array[Byte]]","d":"argparse.core.Printers","k":"object"},
{"l":"argparse/core/Printers$given_Printer_Array$.html#print-fffffe0b","e":false,"i":"","n":"print","t":"print(a: Array[Byte], out: PrintStream): Unit","d":"argparse.core.Printers.given_Printer_Array","k":"def"},
{"l":"argparse/core/Printers$given_Printer_Unit$.html#","e":false,"i":"","n":"given_Printer_Unit","t":"given_Printer_Unit extends Printer[Unit]","d":"argparse.core.Printers","k":"object"},
{"l":"argparse/core/Printers$given_Printer_Unit$.html#print-fffff00d","e":false,"i":"","n":"print","t":"print(a: Unit, out: PrintStream): Unit","d":"argparse.core.Printers.given_Printer_Unit","k":"def"},
{"l":"argparse/core/Printers$given_Printer_Writable$.html#","e":false,"i":"","n":"given_Printer_Writable","t":"given_Printer_Writable extends Printer[Writable]","d":"argparse.core.Printers","k":"object"},
{"l":"argparse/core/Printers$given_Printer_Writable$.html#print-a38","e":false,"i":"","n":"print","t":"print(a: Writable, out: PrintStream): Unit","d":"argparse.core.Printers.given_Printer_Writable","k":"def"},
{"l":"argparse/core/ProductLabels.html#","e":false,"i":"","n":"ProductLabels","t":"ProductLabels[A](labels: List[String])","d":"argparse.core","k":"class"},
{"l":"argparse/core/ProductLabels$.html#","e":false,"i":"","n":"ProductLabels","t":"ProductLabels","d":"argparse.core","k":"object"},
{"l":"argparse/core/ProductLabels$.html#given_ProductLabels_A-fffffe3f","e":false,"i":"","n":"given_ProductLabels_A","t":"given_ProductLabels_A[A <: Product]: ProductLabels[A]","d":"argparse.core.ProductLabels","k":"given"},
{"l":"argparse/core/ProductLabels$.html#of-fffffe3f","e":false,"i":"","n":"of","t":"of[A <: Product]: ProductLabels[A]","d":"argparse.core.ProductLabels","k":"def"},
{"l":"argparse/core/ProductLabels$.html#ofImpl-fffff485","e":false,"i":"","n":"ofImpl","t":"ofImpl[A <: Product : Type](implicit evidence$1: Type[A], qctx: Quotes): Expr[ProductLabels[A]]","d":"argparse.core.ProductLabels","k":"def"},
{"l":"argparse/core/ReadersApi.html#","e":false,"i":"","n":"ReadersApi","t":"ReadersApi extends LowPrioReaders","d":"argparse.core","k":"trait"},
{"l":"argparse/core/ReadersApi.html#FilePathCollectionReader-fffffff3","e":false,"i":"","n":"FilePathCollectionReader","t":"FilePathCollectionReader[Col <: Iterable[FilePath]](implicit factory: Factory[FilePath, Col], pathReader: <none>[FilePath]): Reader[Col]","d":"argparse.core.ReadersApi","k":"def"},
{"l":"argparse/core/ReadersApi.html#IntegralReader-a79","e":false,"i":"","n":"IntegralReader","t":"IntegralReader[N](implicit numeric: Integral[N]): Reader[N]","d":"argparse.core.ReadersApi","k":"def"},
{"l":"argparse/core/ReadersApi.html#JFileCollectionReader-fffffff3","e":false,"i":"","n":"JFileCollectionReader","t":"JFileCollectionReader[Col <: Iterable[File]](implicit factory: Factory[File, Col], pathReader: <none>[File]): Reader[Col]","d":"argparse.core.ReadersApi","k":"def"},
{"l":"argparse/core/ReadersApi.html#JPathCollectionReader-fffffff3","e":false,"i":"","n":"JPathCollectionReader","t":"JPathCollectionReader[Col <: Iterable[Path]](implicit factory: Factory[Path, Col], pathReader: <none>[Path]): Reader[Col]","d":"argparse.core.ReadersApi","k":"def"},
{"l":"argparse/core/ReadersApi.html#Mapping-9a0","e":false,"i":"","n":"Mapping","t":"Mapping[K, V](implicit kr: <none>[K], vr: <none>[V]): Reader[(K, V)]","d":"argparse.core.ReadersApi","k":"def"},
{"l":"argparse/core/ReadersApi.html#OptionReader-a31","e":false,"i":"","n":"OptionReader","t":"OptionReader[A](implicit elementReader: <none>[A]): Reader[Option[A]]","d":"argparse.core.ReadersApi","k":"def"},
{"l":"argparse/core/ReadersApi.html#PathCollectionReader-fffffff3","e":false,"i":"","n":"PathCollectionReader","t":"PathCollectionReader[Col <: Iterable[Path]](implicit factory: Factory[Path, Col], pathReader: <none>[Path]): Reader[Col]","d":"argparse.core.ReadersApi","k":"def"},
{"l":"argparse/core/ReadersApi.html#RelPathCollectionReader-fffffff3","e":false,"i":"","n":"RelPathCollectionReader","t":"RelPathCollectionReader[Col <: Iterable[RelPath]](implicit factory: Factory[RelPath, Col], pathReader: <none>[RelPath]): Reader[Col]","d":"argparse.core.ReadersApi","k":"def"},
{"l":"argparse/core/ReadersApi.html#SubPathCollectionReader-fffffff3","e":false,"i":"","n":"SubPathCollectionReader","t":"SubPathCollectionReader[Col <: Iterable[SubPath]](implicit factory: Factory[SubPath, Col], pathReader: <none>[SubPath]): Reader[Col]","d":"argparse.core.ReadersApi","k":"def"},
{"l":"argparse/core/ReadersApi.html#pathCompleter-0","e":false,"i":"","n":"pathCompleter","t":"pathCompleter: String => Seq[String]","d":"argparse.core.ReadersApi","k":"val"},
{"l":"argparse/core/ReadersApi$BooleanReader$.html#","e":false,"i":"","n":"BooleanReader","t":"BooleanReader extends Reader[Boolean]","d":"argparse.core.ReadersApi","k":"object"},
{"l":"argparse/core/ReadersApi$BooleanReader$.html#read-ffffff54","e":false,"i":"","n":"read","t":"read(a: String): Result[Boolean]","d":"argparse.core.ReadersApi.BooleanReader","k":"def"},
{"l":"argparse/core/ReadersApi$DoubleReader$.html#","e":false,"i":"","n":"DoubleReader","t":"DoubleReader extends Reader[Double]","d":"argparse.core.ReadersApi","k":"object"},
{"l":"argparse/core/ReadersApi$DoubleReader$.html#read-ffffff54","e":false,"i":"","n":"read","t":"read(a: String): Result[Double]","d":"argparse.core.ReadersApi.DoubleReader","k":"def"},
{"l":"argparse/core/ReadersApi$DoubleReader$.html#typeName-0","e":false,"i":"","n":"typeName","t":"typeName: String","d":"argparse.core.ReadersApi.DoubleReader","k":"def"},
{"l":"argparse/core/ReadersApi$DurationReader$.html#","e":false,"i":"","n":"DurationReader","t":"DurationReader extends Reader[Duration]","d":"argparse.core.ReadersApi","k":"object"},
{"l":"argparse/core/ReadersApi$DurationReader$.html#read-ffffff54","e":false,"i":"","n":"read","t":"read(a: String): Result[Duration]","d":"argparse.core.ReadersApi.DurationReader","k":"def"},
{"l":"argparse/core/ReadersApi$DurationReader$.html#typeName-0","e":false,"i":"","n":"typeName","t":"typeName: String","d":"argparse.core.ReadersApi.DurationReader","k":"def"},
{"l":"argparse/core/ReadersApi$FilePathReader$.html#","e":false,"i":"","n":"FilePathReader","t":"FilePathReader extends FsPathReader[FilePath]","d":"argparse.core.ReadersApi","k":"object"},
{"l":"argparse/core/ReadersApi$FilePathReader$.html#read-ffffff54","e":false,"i":"","n":"read","t":"read(a: String): Result[FilePath]","d":"argparse.core.ReadersApi.FilePathReader","k":"def"},
{"l":"argparse/core/ReadersApi$FiniteDurationReader$.html#","e":false,"i":"","n":"FiniteDurationReader","t":"FiniteDurationReader extends Reader[FiniteDuration]","d":"argparse.core.ReadersApi","k":"object"},
{"l":"argparse/core/ReadersApi$FiniteDurationReader$.html#read-ffffff54","e":false,"i":"","n":"read","t":"read(a: String): Result[FiniteDuration]","d":"argparse.core.ReadersApi.FiniteDurationReader","k":"def"},
{"l":"argparse/core/ReadersApi$FiniteDurationReader$.html#typeName-0","e":false,"i":"","n":"typeName","t":"typeName: String","d":"argparse.core.ReadersApi.FiniteDurationReader","k":"def"},
{"l":"argparse/core/ReadersApi$FloatReader$.html#","e":false,"i":"","n":"FloatReader","t":"FloatReader extends Reader[Float]","d":"argparse.core.ReadersApi","k":"object"},
{"l":"argparse/core/ReadersApi$FloatReader$.html#read-ffffff54","e":false,"i":"","n":"read","t":"read(a: String): Result[Float]","d":"argparse.core.ReadersApi.FloatReader","k":"def"},
{"l":"argparse/core/ReadersApi$FloatReader$.html#typeName-0","e":false,"i":"","n":"typeName","t":"typeName: String","d":"argparse.core.ReadersApi.FloatReader","k":"def"},
{"l":"argparse/core/ReadersApi$FsPathReader.html#","e":false,"i":"","n":"FsPathReader","t":"FsPathReader[A] extends Reader[A]","d":"argparse.core.ReadersApi","k":"trait"},
{"l":"argparse/core/ReadersApi$FsPathReader.html#interactiveCompleter-0","e":false,"i":"","n":"interactiveCompleter","t":"interactiveCompleter: String => Seq[String]","d":"argparse.core.ReadersApi.FsPathReader","k":"val"},
{"l":"argparse/core/ReadersApi$FsPathReader.html#standaloneCompleter-0","e":false,"i":"","n":"standaloneCompleter","t":"standaloneCompleter: BashCompleter","d":"argparse.core.ReadersApi.FsPathReader","k":"val"},
{"l":"argparse/core/ReadersApi$FsPathReader.html#typeName-0","e":false,"i":"","n":"typeName","t":"typeName: String","d":"argparse.core.ReadersApi.FsPathReader","k":"def"},
{"l":"argparse/core/ReadersApi$InputStreamReader$.html#","e":false,"i":"","n":"InputStreamReader","t":"InputStreamReader extends Reader[() => InputStream]","d":"argparse.core.ReadersApi","k":"object"},
{"l":"argparse/core/ReadersApi$InputStreamReader$.html#interactiveCompleter-0","e":false,"i":"","n":"interactiveCompleter","t":"interactiveCompleter: String => Seq[String]","d":"argparse.core.ReadersApi.InputStreamReader","k":"val"},
{"l":"argparse/core/ReadersApi$InputStreamReader$.html#read-ffffff54","e":false,"i":"","n":"read","t":"read(a: String): Result[() => InputStream]","d":"argparse.core.ReadersApi.InputStreamReader","k":"def"},
{"l":"argparse/core/ReadersApi$InputStreamReader$.html#typeName-0","e":false,"i":"","n":"typeName","t":"typeName: String","d":"argparse.core.ReadersApi.InputStreamReader","k":"def"},
{"l":"argparse/core/ReadersApi$InstantReader$.html#","e":false,"i":"","n":"InstantReader","t":"InstantReader extends Reader[Instant]","d":"argparse.core.ReadersApi","k":"object"},
{"l":"argparse/core/ReadersApi$InstantReader$.html#read-ffffff54","e":false,"i":"","n":"read","t":"read(a: String): Result[Instant]","d":"argparse.core.ReadersApi.InstantReader","k":"def"},
{"l":"argparse/core/ReadersApi$InstantReader$.html#typeName-0","e":false,"i":"","n":"typeName","t":"typeName: String","d":"argparse.core.ReadersApi.InstantReader","k":"def"},
{"l":"argparse/core/ReadersApi$JavaFileReader$.html#","e":false,"i":"","n":"JavaFileReader","t":"JavaFileReader extends FsPathReader[File]","d":"argparse.core.ReadersApi","k":"object"},
{"l":"argparse/core/ReadersApi$JavaFileReader$.html#read-ffffff54","e":false,"i":"","n":"read","t":"read(a: String): Result[File]","d":"argparse.core.ReadersApi.JavaFileReader","k":"def"},
{"l":"argparse/core/ReadersApi$JavaPathReader$.html#","e":false,"i":"","n":"JavaPathReader","t":"JavaPathReader extends FsPathReader[Path]","d":"argparse.core.ReadersApi","k":"object"},
{"l":"argparse/core/ReadersApi$JavaPathReader$.html#read-ffffff54","e":false,"i":"","n":"read","t":"read(a: String): Result[Path]","d":"argparse.core.ReadersApi.JavaPathReader","k":"def"},
{"l":"argparse/core/ReadersApi$LocalDateReader$.html#","e":false,"i":"","n":"LocalDateReader","t":"LocalDateReader extends Reader[LocalDate]","d":"argparse.core.ReadersApi","k":"object"},
{"l":"argparse/core/ReadersApi$LocalDateReader$.html#read-ffffff54","e":false,"i":"","n":"read","t":"read(a: String): Result[LocalDate]","d":"argparse.core.ReadersApi.LocalDateReader","k":"def"},
{"l":"argparse/core/ReadersApi$LocalDateReader$.html#typeName-0","e":false,"i":"","n":"typeName","t":"typeName: String","d":"argparse.core.ReadersApi.LocalDateReader","k":"def"},
{"l":"argparse/core/ReadersApi$LocalDateTimeReader$.html#","e":false,"i":"","n":"LocalDateTimeReader","t":"LocalDateTimeReader extends Reader[LocalDateTime]","d":"argparse.core.ReadersApi","k":"object"},
{"l":"argparse/core/ReadersApi$LocalDateTimeReader$.html#read-ffffff54","e":false,"i":"","n":"read","t":"read(a: String): Result[LocalDateTime]","d":"argparse.core.ReadersApi.LocalDateTimeReader","k":"def"},
{"l":"argparse/core/ReadersApi$LocalDateTimeReader$.html#typeName-0","e":false,"i":"","n":"typeName","t":"typeName: String","d":"argparse.core.ReadersApi.LocalDateTimeReader","k":"def"},
{"l":"argparse/core/ReadersApi$LocalTime$.html#","e":false,"i":"","n":"LocalTime","t":"LocalTime extends Reader[LocalTime]","d":"argparse.core.ReadersApi","k":"object"},
{"l":"argparse/core/ReadersApi$LocalTime$.html#read-ffffff54","e":false,"i":"","n":"read","t":"read(a: String): Result[LocalTime]","d":"argparse.core.ReadersApi.LocalTime","k":"def"},
{"l":"argparse/core/ReadersApi$LocalTime$.html#typeName-0","e":false,"i":"","n":"typeName","t":"typeName: String","d":"argparse.core.ReadersApi.LocalTime","k":"def"},
{"l":"argparse/core/ReadersApi$OutputStreamReader$.html#","e":false,"i":"","n":"OutputStreamReader","t":"OutputStreamReader extends Reader[() => OutputStream]","d":"argparse.core.ReadersApi","k":"object"},
{"l":"argparse/core/ReadersApi$OutputStreamReader$.html#interactiveCompleter-0","e":false,"i":"","n":"interactiveCompleter","t":"interactiveCompleter: String => Seq[String]","d":"argparse.core.ReadersApi.OutputStreamReader","k":"val"},
{"l":"argparse/core/ReadersApi$OutputStreamReader$.html#read-ffffff54","e":false,"i":"","n":"read","t":"read(a: String): Result[() => OutputStream]","d":"argparse.core.ReadersApi.OutputStreamReader","k":"def"},
{"l":"argparse/core/ReadersApi$OutputStreamReader$.html#typeName-0","e":false,"i":"","n":"typeName","t":"typeName: String","d":"argparse.core.ReadersApi.OutputStreamReader","k":"def"},
{"l":"argparse/core/ReadersApi$PathReader$.html#","e":false,"i":"","n":"PathReader","t":"PathReader extends FsPathReader[Path]","d":"argparse.core.ReadersApi","k":"object"},
{"l":"argparse/core/ReadersApi$PathReader$.html#read-ffffff54","e":false,"i":"","n":"read","t":"read(a: String): Result[Path]","d":"argparse.core.ReadersApi.PathReader","k":"def"},
{"l":"argparse/core/ReadersApi$RangeReader$.html#","e":false,"i":"","n":"RangeReader","t":"RangeReader extends Reader[Range]","d":"argparse.core.ReadersApi","k":"object"},
{"l":"argparse/core/ReadersApi$RangeReader$.html#read-ffffff54","e":false,"i":"","n":"read","t":"read(str: String): Result[Range]","d":"argparse.core.ReadersApi.RangeReader","k":"def"},
{"l":"argparse/core/ReadersApi$RangeReader$.html#typeName-0","e":false,"i":"","n":"typeName","t":"typeName: String","d":"argparse.core.ReadersApi.RangeReader","k":"def"},
{"l":"argparse/core/ReadersApi$ReadableReader$.html#","e":false,"i":"","n":"ReadableReader","t":"ReadableReader extends Reader[Readable]","d":"argparse.core.ReadersApi","k":"object"},
{"l":"argparse/core/ReadersApi$ReadableReader$.html#interactiveCompleter-0","e":false,"i":"","n":"interactiveCompleter","t":"interactiveCompleter: String => Seq[String]","d":"argparse.core.ReadersApi.ReadableReader","k":"val"},
{"l":"argparse/core/ReadersApi$ReadableReader$.html#read-ffffff54","e":false,"i":"","n":"read","t":"read(a: String): Result[Readable]","d":"argparse.core.ReadersApi.ReadableReader","k":"def"},
{"l":"argparse/core/ReadersApi$ReadableReader$.html#typeName-0","e":false,"i":"","n":"typeName","t":"typeName: String","d":"argparse.core.ReadersApi.ReadableReader","k":"def"},
{"l":"argparse/core/ReadersApi$RelPathReader$.html#","e":false,"i":"","n":"RelPathReader","t":"RelPathReader extends FsPathReader[RelPath]","d":"argparse.core.ReadersApi","k":"object"},
{"l":"argparse/core/ReadersApi$RelPathReader$.html#read-ffffff54","e":false,"i":"","n":"read","t":"read(a: String): Result[RelPath]","d":"argparse.core.ReadersApi.RelPathReader","k":"def"},
{"l":"argparse/core/ReadersApi$SubPathReader$.html#","e":false,"i":"","n":"SubPathReader","t":"SubPathReader extends FsPathReader[SubPath]","d":"argparse.core.ReadersApi","k":"object"},
{"l":"argparse/core/ReadersApi$SubPathReader$.html#read-ffffff54","e":false,"i":"","n":"read","t":"read(a: String): Result[SubPath]","d":"argparse.core.ReadersApi.SubPathReader","k":"def"},
{"l":"argparse/core/ReadersApi$ZonedDateTimeReader$.html#","e":false,"i":"","n":"ZonedDateTimeReader","t":"ZonedDateTimeReader extends Reader[ZonedDateTime]","d":"argparse.core.ReadersApi","k":"object"},
{"l":"argparse/core/ReadersApi$ZonedDateTimeReader$.html#read-ffffff54","e":false,"i":"","n":"read","t":"read(a: String): Result[ZonedDateTime]","d":"argparse.core.ReadersApi.ZonedDateTimeReader","k":"def"},
{"l":"argparse/core/ReadersApi$ZonedDateTimeReader$.html#typeName-0","e":false,"i":"","n":"typeName","t":"typeName: String","d":"argparse.core.ReadersApi.ZonedDateTimeReader","k":"def"},
{"l":"argparse/core/StandaloneBashCompletion$.html#","e":false,"i":"","n":"StandaloneBashCompletion","t":"StandaloneBashCompletion","d":"argparse.core","k":"object"},
{"l":"argparse/core/StandaloneBashCompletion$.html#printCommandCompletion-fffff9a7","e":false,"i":"","n":"printCommandCompletion","t":"printCommandCompletion(commandChain: Seq[String], params: Seq[ParamInfo], out: PrintStream): Unit","d":"argparse.core.StandaloneBashCompletion","k":"def"},
{"l":"argparse/core/TextUtils$.html#","e":false,"i":"","n":"TextUtils","t":"TextUtils","d":"argparse.core","k":"object"},
{"l":"argparse/core/TextUtils$.html#kebabify-fffff2ca","e":false,"i":"","n":"kebabify","t":"kebabify(camelCase: String): String","d":"argparse.core.TextUtils","k":"def"},
{"l":"argparse/core/TextUtils$.html#wrap-519","e":false,"i":"","n":"wrap","t":"wrap(in: String, out: StringBuilder, width: Int, newLine: String): Unit","d":"argparse.core.TextUtils","k":"def"},
{"l":"argparse/core/TypesApi.html#","e":false,"i":"","n":"TypesApi","t":"TypesApi","d":"argparse.core","k":"trait"},
{"l":"argparse/core/TypesApi.html#StringReader-0","e":false,"i":"","n":"StringReader","t":"StringReader: Reader[String]","d":"argparse.core.TypesApi","k":"val"},
{"l":"argparse/core/TypesApi$Reader$.html#","e":false,"i":"","n":"Reader","t":"Reader","d":"argparse.core.TypesApi","k":"object"},
{"l":"argparse/core/TypesApi$Reader$$Error.html#","e":false,"i":"","n":"Error","t":"Error(message: String) extends Result[Nothing]","d":"argparse.core.TypesApi.Reader","k":"class"},
{"l":"argparse/core/TypesApi$Reader$$Result.html#","e":false,"i":"","n":"Result","t":"Result[+A]","d":"argparse.core.TypesApi.Reader","k":"trait"},
{"l":"argparse/core/TypesApi$Reader$$Success.html#","e":false,"i":"","n":"Success","t":"Success[A](value: A) extends Result[A]","d":"argparse.core.TypesApi.Reader","k":"class"},
{"l":"argparse/core/TypesApi$Reader.html#","e":false,"i":"","n":"Reader","t":"Reader[A]","d":"argparse.core.TypesApi","k":"trait"},
{"l":"argparse/core/TypesApi$Reader.html#interactiveCompleter-0","e":false,"i":"","n":"interactiveCompleter","t":"interactiveCompleter: String => Seq[String]","d":"argparse.core.TypesApi.Reader","k":"def"},
{"l":"argparse/core/TypesApi$Reader.html#read-ffffff54","e":false,"i":"","n":"read","t":"read(a: String): Result[A]","d":"argparse.core.TypesApi.Reader","k":"def"},
{"l":"argparse/core/TypesApi$Reader.html#standaloneCompleter-0","e":false,"i":"","n":"standaloneCompleter","t":"standaloneCompleter: BashCompleter","d":"argparse.core.TypesApi.Reader","k":"def"},
{"l":"argparse/core/TypesApi$Reader.html#typeName-0","e":false,"i":"","n":"typeName","t":"typeName: String","d":"argparse.core.TypesApi.Reader","k":"def"},
{"l":"argparse/core/VersionSpecificApi.html#","e":false,"i":"","n":"VersionSpecificApi","t":"VersionSpecificApi extends MacroApi","d":"argparse.core","k":"trait"}];