#!/bin/bash

set -o errexit

./mill -i argparse.jvm[3.0.2].docJar

docdir=out/argparse/jvm/3.0.2/docJar.dest/javadoc
git -C "$docdir" init
git -C "$docdir" config user.name "Joe Doc Champion"
git -C "$docdir" config user.email "champ@crashbox.io"
git -C "$docdir" add .
git -C "$docdir" commit -m "A new version is out!"
git -C "$docdir" push -f git@github.com:jodersky/scala-argparse master:gh-pages
