#!/bin/bash

set -o errexit

mill -i cmdr[2.13.3].docJar

docdir=out/cmdr/docJar/dest/javadoc
git -C "$docdir" init
git -C "$docdir" config user.name "Joe Doc Champion"
git -C "$docdir" config user.email "champ@crashbox.io"
git -C "$docdir" add .
git -C "$docdir" commit -m "A new version is out!"
git -C "$docdir" push -f git@github.com:jodersky/cmdr master:gh-pages
