[book]
authors = ["Jakob Odersky"]
language = "en"
multilingual = false
src = "src"
title = "scala-argparse"

[preprocessor.pagetoc]

[build]
create-missing = false

[output.html]
additional-css = ["theme/pagetoc.css"]
additional-js  = ["theme/pagetoc.js"]
git-repository-url = "https://github.com/jodersky/scala-argparse"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/jodersky/scala-argparse/edit/master/book/{path}"
